package com.idcard.gui;

import com.idcard.controller.MainController;
import com.idcard.model.Student;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import javafx.scene.image.ImageView;

import java.io.File;
import java.time.LocalDate;

public class StudentFormController {

    @FXML
    private TextField fullNameField;
    @FXML
    private DatePicker dobPicker;
    @FXML
    private TextField passportField;
    @FXML
    private ComboBox<String> bloodGroupCombo;
    @FXML
    private TextField nationalityField;
    @FXML
    private ComboBox<String> majorCombo;
    @FXML
    private Button uploadButton;
    @FXML
    private Label photoPathLabel;
    @FXML
    private Button generateButton;
    @FXML
    private Label statusLabel;

    @FXML
    private ImageView logoImageView;

    private String selectedPhotoPath;
    private MainController mainController;

    public StudentFormController() {
        this.mainController = new MainController();
    }

    @FXML
    public void initialize() {
        // Clip Logo to Rounded Rectangle
        javafx.scene.shape.Rectangle clip = new javafx.scene.shape.Rectangle(
                logoImageView.getFitWidth(), logoImageView.getFitHeight());
        clip.setArcWidth(20);
        clip.setArcHeight(20);
        logoImageView.setClip(clip);

        bloodGroupCombo.getItems().addAll("A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-");
        majorCombo.getItems().addAll(
                "Chemical", "Civil", "Electrical and Electronics", "Mechanical",
                "Computer Science", "Electronics and Communication", "Biotech",
                "Electronics and Computer", "Mathematics and Computing", "Architectural Engineering");

        // Set DatePicker format
        java.time.format.DateTimeFormatter dateFormatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
        dobPicker.setConverter(new javafx.util.StringConverter<LocalDate>() {
            @Override
            public String toString(LocalDate date) {
                if (date != null) {
                    return dateFormatter.format(date);
                } else {
                    return "";
                }
            }

            @Override
            public LocalDate fromString(String string) {
                if (string != null && !string.isEmpty()) {
                    return LocalDate.parse(string, dateFormatter);
                } else {
                    return null;
                }
            }
        });
    }

    @FXML
    private void handleUploadPhoto() {
        FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Select Student Photo");
        fileChooser.getExtensionFilters().addAll(
                new FileChooser.ExtensionFilter("Image Files", "*.png", "*.jpg", "*.jpeg"));

        Stage stage = (Stage) uploadButton.getScene().getWindow();
        File file = fileChooser.showOpenDialog(stage);

        if (file != null) {
            selectedPhotoPath = file.getAbsolutePath();
            photoPathLabel.setText(file.getName());
        }
    }

    @FXML
    private void handleGenerate() {
        try {
            // 1. Collect Data
            String fullName = fullNameField.getText();
            LocalDate dob = dobPicker.getValue();
            String passport = passportField.getText();
            String bloodGroup = bloodGroupCombo.getValue();
            String nationality = nationalityField.getText();
            String major = majorCombo.getValue();

            // 2. Basic Validation
            if (fullName.isEmpty() || dob == null || passport.isEmpty() || bloodGroup == null ||
                    nationality.isEmpty() || major == null || selectedPhotoPath == null) {
                showAlert(Alert.AlertType.ERROR, "Validation Error", "All fields are required, including photo.");
                return;
            }

            // Auto-set year to current year
            int yearOfStudy = LocalDate.now().getYear();

            // 3. Create Student Object
            // Note: ID is generated by controller, so passing null/empty for now
            Student student = new Student(fullName, dob, passport, bloodGroup, nationality, selectedPhotoPath, null,
                    major, yearOfStudy);

            // 4. Call Controller
            statusLabel.setText("Generating...");
            mainController.generateIDCard(student, selectedPhotoPath);

            statusLabel.setText("ID Card Generated Successfully!");
            showAlert(Alert.AlertType.INFORMATION, "Success", "ID Card generated for " + fullName);

        } catch (Exception e) {
            statusLabel.setText("Error occurred.");
            showAlert(Alert.AlertType.ERROR, "Error", "An error occurred: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void showAlert(Alert.AlertType type, String title, String content) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(content);
        alert.showAndWait();
    }
}
